# Generated by Django 6.0.4 on 2026-04-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('scooter', 'Scooter')], max_length=20),
        ),
    ]
